"use client";
import {useEffect,useState} from "react";
import {CalendarDays,Clock3,ChevronDown,Activity} from "lucide-react";
import {getUpcoming,getPrediction} from "../lib/api";
import PredictionCard from "./components/PredictionCard";

export default function Home(){
 const [matches,setMatches]=useState<any[]>([]); const [selected,setSelected]=useState<any>(); const [p,setP]=useState<any>(); const [loading,setLoading]=useState(false);
 useEffect(()=>{getUpcoming().then(x=>{setMatches(Array.isArray(x)?x:[]);setSelected(Array.isArray(x)&&x.length?x[0]:undefined)}).catch(console.error)},[]);
 useEffect(()=>{if(selected){setLoading(true);getPrediction(selected.id).then(setP).finally(()=>setLoading(false))}},[selected]);
 return <main className="min-h-screen bg-[#050b16] px-4 py-8 md:px-8"><div className="mx-auto max-w-5xl"><header className="mb-7 flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-sky-400"><Activity className="h-4 w-4"/> Football Analytics</div><h1 className="mt-2 text-3xl font-black tracking-tight text-white md:text-4xl">Match Predictor</h1><p className="mt-1 text-sm text-slate-500">Probabilistic predictions from form, goals, corners and xG.</p></div><div className="relative"><select className="appearance-none rounded-xl border border-slate-800 bg-[#0a1220] px-4 py-3 pr-10 text-sm text-slate-200 outline-none" value={selected?.id||""} onChange={e=>setSelected(matches.find(m=>m.id===Number(e.target.value)))}>{matches.map(m=><option key={m.id} value={m.id}>{m.home} vs {m.away}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-3.5 h-4 w-4 text-slate-500"/></div></header>
 {selected&&<div className="mb-6 rounded-3xl border border-slate-800 bg-gradient-to-b from-[#0d1728] to-[#080f1c] p-6"><div className="flex items-center justify-center gap-5 md:gap-14"><Team logo={selected.home_logo} name={selected.home}/><div className="text-center"><div className="text-xs font-medium text-slate-500">{selected.league}</div><div className="mt-2 flex items-center gap-2 text-sm text-slate-300"><CalendarDays className="h-4 w-4"/>{new Date(selected.kickoff).toLocaleDateString(undefined,{weekday:"long",day:"2-digit",month:"long",year:"numeric"})}</div><div className="mt-1 flex items-center justify-center gap-2 text-sm font-semibold text-white"><Clock3 className="h-4 w-4 text-sky-400"/>{new Date(selected.kickoff).toLocaleTimeString(undefined,{hour:"2-digit",minute:"2-digit",hour12:false})}</div></div><Team logo={selected.away_logo} name={selected.away}/></div></div>}
 {loading?<div className="py-20 text-center text-slate-500">Analyzing match data…</div>:p&&<div className="grid gap-4"><PredictionCard title="Winner" outcome={`Double Chance: ${p.winner.double_chance}`} confidence={p.winner.confidence} risk={p.winner.risk} insight={p.winner.insight}/><PredictionCard title="Over / Under" outcome={p.over_under.outcome} confidence={p.over_under.confidence} risk={p.over_under.risk} insight={p.over_under.insight}/><PredictionCard title="Corners" outcome={p.corners.outcome} confidence={p.corners.confidence} risk={p.corners.risk} insight={p.corners.insight}/></div>}
 <footer className="mt-8 text-center text-xs text-slate-600">Model version: {p?.model_version||"—"} · Probabilities are estimates, not guarantees.</footer></div></main>
}
function Team({logo,name}:{logo?:string;name:string}){return <div className="flex w-28 flex-col items-center gap-3 text-center"><div className="flex h-16 w-16 items-center justify-center rounded-full border border-slate-700 bg-slate-900 p-2">{logo?<img src={logo} alt="" className="h-full w-full object-contain"/>:<span className="text-lg font-black text-slate-500">{name[0]}</span>}</div><div className="text-sm font-bold text-white">{name}</div></div>}
